site_name: OtterSMP
theme:
  name: material
  palette:
    scheme: slate
    primary: custom
    accent: custom
  logo: assets/otter_1240x.png
  favicon: assets/otter_1240x.png
  features:
    - navigation.sections
    - navigation.path
    - navigation.indexes
    - search.highlight
    - search.suggest
    - navigation.tabs
    - header.autohide
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list

extra:
  generator: false
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.gg/ottersmp

extra_css:
  - stylesheets/extra.css

copyright: Copyright &copy; 2024 OtterSMP

nav:
  - Home:
    - Home: index.md
    - Currency: Currency.md
    - Dungeons: Dungeons.md
    - Milestones: Milestones.md
    - Ranks: Ranks.md
    - Cosmetics: Cosmetics.md
    - Campaign: Campaign.md 
    - Commanders: Commanders.md
    - Races: Races.md
    - Crates: Crates.md
    - Stalls: Stalls.md
    - Voteparty: Voteparty.md
    - Warps: Warps.md
  - Items:
    - Star Shards: items/starshards.md
  - NPC's:
    - Annie the Blacksmith: NPCs/Annie the Blacksmith.md
    - Asuna: NPCs/Asuna.md
    - Jazmine: NPCs/Jazmine.md
    - Angel: NPCs/Angel.md
    - Taylor: NPCs/Taylor.md
    - Sarah: NPCs/Sarah.md
    - Joshua: NPCs/Joshua.md
    - Abby: NPCs/Abby.md
  - Vendors:
    - Vendors: vendors/Vendors.md
    - Starfox: vendors/Starfox.md
    - Jess: vendors/Jess.md