site_name: Mobcraft
theme:
  name: material
  palette:
    scheme: slate
    primary: green
    accent: teal
  logo: assets/logo.png
  favicon: assets/logo.png
  features:
    - navigation.sections
    - navigation.path
    - navigation.indexes
    - search.highlight
    - search.suggest
    - navigation.tabs
    - header.autohide
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

extra:
  generator: false
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.com/invite/R7WszeZ6wQ

copyright: Copyright &copy; 2024 Mobcraft

nav:
  - Guide: 'guide.md'
  - Protocol: 'protocol.md'